import type { FormTemplate, FormTheme } from "./schema";

const base: FormTheme = {
  pageBg: "#FAF8F5",
  cardBg: "#ffffff",
  primary: "#217E79",
  text: "#253338",
  muted: "#66797D",
  inputBg: "#ffffff",
  inputBorder: "#E1DFD7",
  radius: 10,
  width: 640,
  fontSize: 14,
  inputStyle: "outline",
  cardBorder: true,
  cardShadow: true,
};
const t = (over: Partial<FormTheme>): FormTheme => ({ ...base, ...over });

/** The ready-made registration form designs (Setup → Event Form Design). */
export const BUILT_IN_TEMPLATES: FormTemplate[] = [
  {
    id: "classic-teal",
    name: "Classic Teal",
    description: "Teal banner, one field per row. The safe default.",
    builtIn: true,
    theme: t({}),
    layout: [
      { type: "banner", props: { align: "left" } },
      { type: "text" },
      { type: "fields", props: { width: "full" } },
      { type: "submit" },
    ],
  },
  {
    id: "minimal-white",
    name: "Minimal White",
    description: "No banner, underlined inputs, lots of white space.",
    builtIn: true,
    theme: t({ pageBg: "#ffffff", cardBorder: false, cardShadow: false, primary: "#253338", inputStyle: "underline", radius: 4, width: 560 }),
    layout: [
      { type: "heading", props: { text: "{{eventName}}", size: "xl" } },
      { type: "eventInfo", props: { layout: "row" } },
      { type: "divider" },
      { type: "fields", props: { width: "full" } },
      { type: "spacer", props: { height: 8 } },
      { type: "submit", props: { label: "Confirm registration", align: "left" } },
    ],
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Dark page with an amber accent — good for evening events.",
    builtIn: true,
    theme: t({ pageBg: "#0F172A", cardBg: "#1E293B", primary: "#F59E0B", text: "#F8FAFC", muted: "#94A3B8", inputBg: "#0F172A", inputBorder: "#334155", cardBorder: false, radius: 12 }),
    layout: [
      { type: "heading", props: { text: "{{eventName}}", size: "xl", align: "center" } },
      { type: "text", props: { text: "{{eventDate}} · {{venue}}", align: "center" } },
      { type: "divider" },
      { type: "fields", props: { width: "half" } },
      { type: "submit", props: { label: "Reserve my seat" } },
    ],
  },
  {
    id: "sunrise",
    name: "Sunrise",
    description: "Warm orange-to-pink banner with rounded, filled inputs.",
    builtIn: true,
    theme: t({ pageBg: "#FFF7ED", primary: "#EA580C", inputStyle: "filled", inputBg: "#FFF1E6", inputBorder: "#FED7AA", radius: 14, cardBorder: false }),
    layout: [
      { type: "banner", props: { bg: "#F97316", bg2: "#DB2777", align: "center", padding: 36 } },
      { type: "text", props: { align: "center" } },
      { type: "fields", props: { width: "full" } },
      { type: "submit", props: { label: "Count me in" } },
    ],
  },
  {
    id: "corporate-blue",
    name: "Corporate Blue",
    description: "Two-column fields with event details up top. Suits conferences.",
    builtIn: true,
    theme: t({ pageBg: "#EEF2F9", primary: "#2249B7", radius: 6, width: 760, inputBorder: "#CBD5E1" }),
    layout: [
      { type: "banner", props: { bg: "#1E3A8A", subtitle: "{{organizer}}", padding: 24 } },
      { type: "eventInfo", props: { layout: "row" } },
      { type: "divider" },
      { type: "heading", props: { text: "Attendee details", size: "md" } },
      { type: "fields", props: { width: "half" } },
      { type: "consent" },
      { type: "submit", props: { label: "Submit registration", align: "right" } },
    ],
  },
  {
    id: "soft-lavender",
    name: "Soft Lavender",
    description: "Gentle purple tones with very rounded corners.",
    builtIn: true,
    theme: t({ pageBg: "#F5F3FF", primary: "#7C3AED", inputStyle: "filled", inputBg: "#F3EEFF", inputBorder: "#DDD6FE", radius: 18, cardBorder: false }),
    layout: [
      { type: "heading", props: { text: "You're invited", size: "sm", align: "center", color: "#7C3AED" } },
      { type: "heading", props: { text: "{{eventName}}", size: "xl", align: "center" } },
      { type: "text", props: { text: "{{eventDate}} · {{venue}}", align: "center" } },
      { type: "spacer", props: { height: 8 } },
      { type: "fields", props: { width: "full" } },
      { type: "submit", props: { label: "Register" } },
    ],
  },
  {
    id: "bold-red",
    name: "Bold Red",
    description: "Big headline and the fee table shown before the form.",
    builtIn: true,
    theme: t({ pageBg: "#FEF2F2", primary: "#DC2626", radius: 8, inputBorder: "#FECACA" }),
    layout: [
      { type: "banner", props: { bg: "#B91C1C", align: "left", padding: 32 } },
      { type: "fees", props: { title: "Choose your pass" } },
      { type: "heading", props: { text: "Your details", size: "md" } },
      { type: "fields", props: { width: "full" } },
      { type: "consent" },
      { type: "submit", props: { label: "Register now" } },
    ],
  },
  {
    id: "forest-green",
    name: "Forest Green",
    description: "Deep green banner with stacked event details.",
    builtIn: true,
    theme: t({ pageBg: "#F0FDF4", primary: "#15803D", radius: 10, inputBorder: "#BBF7D0" }),
    layout: [
      { type: "banner", props: { bg: "#14532D", align: "center", subtitle: "" } },
      { type: "eventInfo", props: { layout: "stack" } },
      { type: "divider" },
      { type: "fields", props: { width: "full" } },
      { type: "submit", props: { label: "Join the event" } },
    ],
  },
  {
    id: "mono-slate",
    name: "Mono Slate",
    description: "Square corners and strong borders. Formal and compact.",
    builtIn: true,
    theme: t({ pageBg: "#E2E8F0", primary: "#0F172A", radius: 0, cardShadow: false, inputBorder: "#94A3B8", width: 720, fontSize: 13 }),
    layout: [
      { type: "heading", props: { text: "{{eventName}}", size: "lg" } },
      { type: "text", props: { text: "Registration form — {{eventDate}}" } },
      { type: "divider", props: { thickness: 2, color: "#0F172A" } },
      { type: "fields", props: { width: "half" } },
      { type: "consent" },
      { type: "submit", props: { label: "SUBMIT", align: "left" } },
    ],
  },
  {
    id: "festive-gold",
    name: "Festive Gold",
    description: "Cream and gold, centred — for celebrations and cultural events.",
    builtIn: true,
    theme: t({ pageBg: "#FFFBEB", cardBg: "#FFFDF5", primary: "#B45309", text: "#451A03", muted: "#92400E", inputBorder: "#FDE68A", radius: 12, width: 600 }),
    layout: [
      { type: "banner", props: { bg: "#D97706", bg2: "#B45309", align: "center", padding: 34 } },
      { type: "text", props: { text: "We would love to have you with us. Please register below.", align: "center" } },
      { type: "fees", props: { title: "Entry" } },
      { type: "fields", props: { width: "full" } },
      { type: "submit", props: { label: "Register" } },
    ],
  },
  {
    id: "landing-split",
    name: "Landing — Picture beside form",
    description: "Full page: picture or video panel on the left, form on the right, with header and footer.",
    builtIn: true,
    theme: t({
      pageBg: "#ffffff", cardBorder: false, cardShadow: false, width: 520, layout: "split", overlay: 35,
      heroTitle: "{{eventName}}", heroText: "{{eventDate}} · {{venue}}",
      header: { show: true, logo: "", title: "{{organizer}}", bg: "#ffffff", color: "#253338" },
      footer: { show: true, text: "© {{organizer}}", bg: "#253338", color: "#ffffff" },
    }),
    layout: [
      { type: "heading", props: { text: "Register now", size: "lg" } },
      { type: "text" },
      { type: "fields", props: { width: "full" } },
      { type: "consent" },
      { type: "submit" },
    ],
  },
  {
    id: "landing-cover",
    name: "Landing — Full background",
    description: "Full page: a picture or video fills the background, the form floats over it.",
    builtIn: true,
    theme: t({
      pageBg: "#0F172A", cardBorder: false, width: 560, radius: 14, layout: "card", overlay: 45,
      header: { show: true, logo: "", title: "{{organizer}}", bg: "#0F172A", color: "#ffffff" },
      footer: { show: true, text: "© {{organizer}}", bg: "#0F172A", color: "#ffffff" },
    }),
    layout: [
      { type: "heading", props: { text: "{{eventName}}", size: "xl", align: "center" } },
      { type: "eventInfo", props: { layout: "row" } },
      { type: "divider" },
      { type: "fields", props: { width: "half" } },
      { type: "submit" },
    ],
  },
];

export const DEFAULT_TEMPLATE = BUILT_IN_TEMPLATES[0];
